#!/usr/bin/env node

/* 
 * Test Script - for testing!
 */

try {
    var reporter = require("nodeunit").reporters.default;
} catch (e) {
    console.log("Cannot find nodeunit module");
}

var testModules = process.argv.slice(2);

// Run each test module
testModules.forEach( function (module) {
    reporter.run([module]);
});
